name: JIRA Title PR Synchronizer
author: On Running
branding:
  icon: activity
  color: blue
description: Add Jira ticket to PR title / add links to PR description
inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  jira-account:
    description: Subdomain used for jira link (i.e. foobar => https://foobar.atlassian.net/browse/ABC-123)
    required: true
  ticket-regex:
    description: Regex to match jira ticket in branch name (i.e. ^ABC-\d+)
    required: true
runs:
  using: node16
  main: dist/index.js
